config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  root 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    
    before_destroy :not_referenced_by_any_line_item
    belongs_to :user, optional: true 
    has_many :line_items
    mount_uploader :image, ImageUploader

    validates :title, :price , presence: true
    validates :description, length: { maximum: 500, too_long: "%{count} is the max limit allowed" }
    validates :title, length: { maximum: 50, too_long: "%{count} is the max limit allowed" }
    validates :price, numericality: { only_decimal: true }, length: { maximum: 8 }


    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
            errors.add(:base, "Line items present")
            throw :abort
        end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :showS]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("created_at desc")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

    def product_author(product)
        user_signed_in? && current_user.id == product_user.id
    end

end

app/views/products/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @product, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input product-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', products_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Product
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Browse the latest Products on GameShop!
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="instrument-index-grid pt4">
  <% @products.each do |product| %>

    <div class="product border-light">
      <div class="product-thumb">
        <% if product.image_url(:thumb) %>
          <%= link_to image_tag(product.image_url(:thumb)), product %>
        <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to product.title, product %></h3>

      <!--<p class="has-text-gray fg pt1">Sold by <%#= product.user.name %></p>-->

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(product.price) %></p>

      <%# if product_author(product) %>
         <%= link_to 'Edit', edit_product_path(product), class: "button is-small" %>
         <%= link_to 'Delete', product, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
      <%# end %>

    </div>
  </div>
  <% end %>
</div>

app/views/products/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell a product
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

app/views/products/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section product-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @product.title %></h1>

     <div class="feature-image">
       <%#= image_tag(@product.image_url(:default)) %>
     </div>
     <div class="content pa4 mt3 bg-white border-radius-3">

        <h3 class="subtitle is-4">Description</h3>
        <%= @product.description %>
       </div>
     </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@product.price) %></h4>

        <%= button_to 'Add to cart', line_items_path(product_id: @product), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_product_path(@product), class: 'button' %>

</section>